#MY BTOP WINDOW RULE
windowrule = float on, match:class alacritty-btop
windowrule = workspace 1, match:class alacritty-btop
windowrule = move 75% 70%, match:class alacritty-btop
windowrule = size 700 400, match:class alacritty-btop
windorule = below on, match:class alacritty-btop

#BTOP EXEC
exec-once = alacritty --class alacritty-btop -e btop
