$CITY = Kolkata
$COUNTRY = India
$WALLPAPER_PATH = /home/user/.config/wallpapersymlink.jpg
$USER = sam

$fn_bold = SF Pro Display Bold
$fn_semi = SF Pro Display Semibold
$fn_text = SF Pro Text Semibold

#BACKGROUND
background {
    path = $WALLPAPER_PATH
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

#GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

#INPUT FIELD
input-field {
    size = 170, 45
    outline_thickness = 2
    dots_size = 0.2 #Scale of input-field height, 0.2-0.8
    dots_spacing = 0.2 #Scale of dots absolute-size, 0.0-1.0
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(100, 114, 125, 0.4)
    font_color = rgba(200, 200, 200, 1)
    fade_on_empty = false
    font_family = $fn_semi
    placeholder_text = Enter Password  #"<span foreground='#ffffff #ffffff99'>Enter Password</span>"
    hide_input = false
    position = 0, -425
    halign = center 
    valign  = center 
    
}

# TIME (Large 20:19)
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 0.9)
    font_size = 95
    font_family = $fn_bold
    position = 0, 270
    halign = center
    valign = center
}

# DATE (Wednesday, July 09)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 0.8)
    font_size = 24
    font_family = $fn_semi
    position = 0, 380
    halign = center
    valign = center
}

#Profile-Photo
image {
    path = /home/user/Downloads/pfp.jpg
    border_color = 0xffdddddd
    border_size = 0
    size = 110
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, -265
    halign = center
    valign = center
}

#USER
label {
    text =$USER
    color = rgba(216, 222, 233, 0.70)
    font_size = 20
    font_family = $fn_semi
    position = 0, -360
    halign = center
    valign = center
}
#CURRENT SONG (SPOTIFY)
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/hyprlock/spotify-playing.sh
    color = rgba(255, 255, 255, 0.7)
    font_size = 18
    font_family = $fn_semi
    position = 50, -500
    halign = left
    valign = center
}
